"""
Write docs/PROMPTS.md: every prompt and model instruction the app sends at inference,
copied from the code so the document cannot drift from what actually runs.

    python tools/export_prompts.py

Re-run it after changing refine.py, stageA_prompt.py or document.py.
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
os.chdir(ROOT)

import document          # noqa: E402
import refine            # noqa: E402
import stageA_prompt     # noqa: E402
from llm import LOCAL_DEFAULTS   # noqa: E402


def block(text, lang="text"):
    return f"```{lang}\n{text.rstrip()}\n```\n"


def schema(s):
    return block(json.dumps(s["schema"], indent=2), "json")


def main():
    fewshot = stageA_prompt.load_examples()
    out = []
    w = out.append

    w("# Prompts and model instructions\n")
    w("_Generated by `tools/export_prompts.py` from the code. Do not edit by hand; "
      "change the code and re-run the script._\n")
    w("The app sends four prompts. Every call asks for JSON. On the API backend the schemas "
      "below are sent as the `json_schema` response format. On the local backend there is no "
      "constrained decoding: the line \"Respond with the JSON object only, no other text.\" is "
      "appended to the last user message, the reply is parsed, and if it is not valid JSON the "
      "model is asked once to correct it. No model weights are changed: all behaviour comes "
      "from these prompts plus the code checks described in the README.\n")
    w("| Stage | Code | Default local model | Messages | Temperature |\n"
      "|---|---|---|---|---|\n"
      f"| Refinement | `refine.py` | `{LOCAL_DEFAULTS['refine'][0]}` ({LOCAL_DEFAULTS['refine'][1]}) "
      "| system, worked example (user + assistant), batch | 0 |\n"
      f"| Stage A extract | `stageA_prompt.py` | `{LOCAL_DEFAULTS['doc'][0]}` ({LOCAL_DEFAULTS['doc'][1]}) "
      f"| system, {len(fewshot)} AMI examples + 1 synthetic (user + assistant each), transcript | 0 |\n"
      f"| Stage D verify | `document.py` | same as Stage A | system, items | 0 |\n"
      f"| Stage C write | `document.py` | same as Stage A | system, record + transcript | 0.2 |\n")
    w("Local generation: greedy decoding at temperature 0; at temperature > 0, sampling with "
      "top_p 0.9. Each model's own chat template is applied by `transformers`.\n")

    # ---- refinement
    w("## 1. Refinement (language model 1)\n")
    w("Corrects speech-recognition errors. Called once per batch of "
      "20 lines (`prompts/refine_config.json`), with the glossary and the last 3 corrected "
      "lines as context.\n")
    w("### System\n")
    w(block(refine.SYSTEM))
    w("### Worked example: user\n")
    w(block(refine.DEMO_USER))
    w("### Worked example: assistant\n")
    w(block(json.dumps(json.loads(refine.DEMO_ASSISTANT), indent=1), "json"))
    w("### Real request: user (format)\n")
    w(block(refine.format_lines(
        [{"id": 12, "hypotheses": ["first hypothesis of line 12", "second hypothesis"]},
         {"id": 13, "hypotheses": ["only hypothesis of line 13"]}],
        glossary=["Kubernetes", "PostgreSQL"],
        context=["[11] Previous line, already corrected."])))
    w("### Output schema\n")
    w(schema(refine.SCHEMA))
    w("After the call, `refine.guard()` checks every line: an empty answer, a line far from "
      "every hypothesis, or a number or negation that no hypothesis supports reverts to "
      "Whisper's top hypothesis and is flagged.\n")

    # ---- stage A
    w("## 2. Stage A: extraction (language model 2)\n")
    w("Extracts topics, decisions and tasks with cited line numbers. Long transcripts are sent "
      "in chunks of 100 lines with 10 lines of overlap on the local backend "
      "(`STAGEA_CHUNK_LINES`).\n")
    w("### System\n")
    w(block(stageA_prompt.SYSTEM))
    w("### User turn (format used for the examples and the real transcript)\n")
    w(block(stageA_prompt.user_turn(["[1] SPEAKER_00: first line of the transcript",
                                     "[2] SPEAKER_01: second line"])))
    w("### Few-shot examples\n")
    w(f"{len(fewshot)} excerpts from the AMI Meeting Corpus (`stageA/stageA_fewshot.json`, built "
      "by `build_stageA_prompts_from_ami.py`), then one hand-written example. Each is sent as a "
      "user turn in the format above followed by the gold JSON as the assistant turn. The full "
      "assembled prompt is in `stageA/stageA_example_prompt.txt`.\n")
    if fewshot:
        rows = ["| Example | Lines | Topics | Decisions | Tasks |", "|---|---|---|---|---|"]
        for ex in fewshot:
            g = ex["target"]
            a, b = ex.get("window", [0, len(ex["lines"])])
            rows.append(f"| AMI {ex['meeting']}, lines {a}-{b} | {len(ex['lines'])} | "
                        f"{len(g['topics'])} | {len(g['decisions'])} | {len(g['tasks'])} |")
        w("\n".join(rows) + "\n")
    w("The hand-written example covers what AMI never labels: a proposal that was not agreed "
      "and a task with no owner.\n")
    w(block("\n".join(stageA_prompt.SYNTHETIC_EXAMPLE["lines"])))
    w(block(json.dumps(stageA_prompt.SYNTHETIC_EXAMPLE["target"], indent=1), "json"))
    w("If a request is too large for the model, the examples are dropped in two steps "
      "(AMI excerpts first, then the synthetic one) and the run is flagged "
      "`smaller_prompt_used`.\n")
    w("### Output schema\n")
    w(schema(stageA_prompt.SCHEMA))
    w("Stage B (`stage_b_filter`, code only) then drops items with no valid line, demotes "
      "'agreed' decisions with no confirmation line to proposals, and clears owners or deadlines "
      "not stated on the cited lines.\n")

    # ---- stage D
    w("## 3. Stage D: verification (language model 2)\n")
    w("Up to 15 items per call; each item is sent with only the transcript lines it cites. "
      "Unsupported items are removed and listed as flags.\n")
    w("### System\n")
    w(block(document.VERIFY_SYSTEM))
    w("### User turn (format; items separated by `---`)\n")
    w(block("id: t0\ntype: task\ntext: Fix the Android login token refresh bug.\n"
            "owner: Priya\ndeadline: Thursday\ncited lines:\n"
            "[2] SPEAKER_01: Yeah, it's the token refresh. Priya, can you take that?\n"
            "[3] SPEAKER_02: Sure, I'll fix it by Thursday."))
    w("### Output schema\n")
    w(schema(document.VERIFY_SCHEMA))

    # ---- stage C
    w("## 4. Stage C: writing (language model 2)\n")
    w("Writes the summary and the minutes from the verified record. Decisions and action items "
      "in the output files are copied from the record, not from this answer.\n")
    w("### System\n")
    w(block(document.WRITE_SYSTEM))
    w("### User turn (format)\n")
    w(block('Verified record:\n{"decisions": [...], "proposals": [...], "tasks": [...]}\n\n'
            "Transcript by topic:\n\n## Topic: <title> (lines 1-40)\n[1] SPEAKER_00: ...\n"
            "...\n\n## Topic: <title> (lines 41-90)\n..."))
    w("Transcript excerpts are capped at 60,000 characters in total; if the model rejects the "
      "request as too large they are cut to 15,000, then 5,000.\n")
    w("### Output schema\n")
    w(schema(document.WRITE_SCHEMA))

    os.makedirs("docs", exist_ok=True)
    with open(os.path.join("docs", "PROMPTS.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print("Wrote docs/PROMPTS.md")


if __name__ == "__main__":
    main()
